version: '3.8'
services:
  ros2:
    image: ros:jazzy
    container_name: turtlebot3_project
    volumes:
      - ./src:/workspace/src
      - ./install:/workspace/install
      - ./log:/workspace/log
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        apt update &&
        apt install -y ros-jazzy-navigation2 ros-jazzy-slam-toolbox ros-jazzy-turtlebot3-gazebo python3-rosdep python3-colcon-common-extensions python3-numpy &&
        rosdep init &&
        rosdep update &&
        if [ -d /workspace/src ]; then
          rosdep install --from-paths src --ignore-src -r -y &&
          cd /workspace &&
          rm -rf build install log &&
          colcon build &&
          source install/setup.bash &&
          ros2 launch slam_toolbox online_async_launch.py;
        else
          echo 'Error: /workspace/src is empty or missing' &&
          exit 1;
        fi
      "
  gazebo:
    image: ros:jazzy
    container_name: turtlebot3_gazebo
    volumes:
      - ./src:/workspace/src
      - ./install:/workspace/install
      - ./log:/workspace/log
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /workspace/install/setup.bash &&
        ros2 launch turtlebot3_gazebo turtlebot3_world.launch.py
      "
  rviz:
    image: ros:jazzy
    container_name: turtlebot3_rviz
    volumes:
      - ./src:/workspace/src
      - ./install:/workspace/install
      - ./log:/workspace/log
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /workspace/install/setup.bash &&
        ros2 run rviz2 rviz2 -d /workspace/src/turtlebot3/turtlebot3_description/rviz/urdf.rviz
      "
  teleop:
    image: ros:jazzy
    container_name: turtlebot3_teleop
    volumes:
      - ./src:/workspace/src
      - ./install:/workspace/install
      - ./log:/workspace/log
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /workspace/install/setup.bash &&
        ros2 run teleop_twist_keyboard teleop_twist_keyboard
      "
  path:
    image: ros:jazzy
    container_name: turtlebot3_path
    volumes:
      - ./src:/workspace/src
      - ./install:/workspace/install
      - ./log:/workspace/log
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /workspace/install/setup.bash &&
        ros2 run car_path_solution path_node
      "
  problem:
    image: ros:jazzy
    container_name: turtlebot3_problem
    volumes:
      - ./src:/workspace/src
      - ./install:/workspace/install
      - ./log:/workspace/log
    environment:
      - DISPLAY=${DISPLAY}
      - TURTLEBOT3_MODEL=burger
      - LIBGL_ALWAYS_SOFTWARE=1
    network_mode: host
    privileged: true
    devices:
      - /dev/dri:/dev/dri
    command: >
      bash -c "
        source /opt/ros/jazzy/setup.bash &&
        source /workspace/install/setup.bash &&
        ros2 run solution_problem problem_node
      "
